### ISSUE TITLE
App doesn't fetch any data from API

### ISSUE THREAD

**Issue by b-galazka** [lupuuss/PlanLekcji#1]
Fetching error is displayed.

**Comment by alan-mroczek** [comment]
Did you try to ping server with some kind of REST Client? Can you try and share details?

**Comment by alan-mroczek** [comment]
@b-galazka ?

**Comment by b-galazka** [comment]
@alan-mroczek I tried and it didn't work either. I think we can close this issue.

**Comment by alan-mroczek** [comment]
@b-galazka thanks! 👍
